version: '2'
services:
  webapp-exercise:
    build: .
    command: npm start
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_USER: postgres
      DATABASE_PASS:
      POSTGRES_MASTER_SERVICE_HOST: postgres
      POSTGRES_MASTER_SERVICE_PORT: 5432
      DATABASE_NAME: development
      GOOGLE_CONSUMER_KEY: 206888294905-qvs2m4oudqq7k5cpac4vc6lf1racaffh.apps.googleusercontent.com
      GOOGLE_CONSUMER_SECRET: avGpzlPDF-vcLhhl4AB4c68w
      GOOGLE_OAUTH_CALLBACK_URL: http://localhost:3000/auth/google/callback
    ports:
    - 3000:3000
    links:
    - postgres

  postgres:
    build: docker/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: development
    ports:
    - 5432
