# Copyright 2016, Z Lab Corporation. All rights reserved.

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: webapp-exercise
data:
  0-init-users-table.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id VARCHAR(30) PRIMARY KEY,
      name VARCHAR(256),
      email VARCHAR(256)
    );
  1-init-messages-table.sql: |
    CREATE TABLE IF NOT EXISTS messages (
      mid SERIAL PRIMARY KEY,
      uid VARCHAR(30) REFERENCES users(id) NOT NULL,
      text VARCHAR(140) NOT NULL,
      created TIMESTAMP,
      updated TIMESTAMP
    );
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-master
  namespace: webapp-exercise
  labels:
    app: postgres
    role: master
    tier: backend
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
    role: master
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-master
  namespace: webapp-exercise
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        role: master
        tier: backend
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: NODE_ENV
          value: development
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value:
        - name: POSTGRES_DB
          value: development
        - name: PGDATA
          value: /data
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data-storage
          mountPath: /data
        - name: script-storage
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
      - name: data-storage
        emptyDir: {}
      - name: script-storage
        configMap:
          name: postgres-init-script
