# Copyright 2016, Z Lab Corporation. All rights reserved.

apiVersion: v1
kind: Service
metadata:
  name: postgres-master
  labels:
    app: postgres
    role: master
    tier: backend
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
    role: master
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        role: master
        tier: backend
    spec:
      containers:
      - name: postgres
        image: kkohtaka/postgres-webapp-exercise
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: NODE_ENV
          value: development
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value:
        - name: POSTGRES_DB
          value: development
        ports:
        - containerPort: 5432
